### ISSUE TITLE
Lets make it global!

### ISSUE THREAD

**Issue by Nick-infinity** [jalotra/Nit-Kurukshetra-OnCampus-Placements-2021#1]
it would be great if we can collect data for multiple unis and colleges and host it at single place! What say?

**Comment by jalotra** [comment]
I don't see the need to do something like that. 
The Objective of this repo is to cater to Juniors of this Uni. I just wanted to give a formal proof to the myths  : 
1. 7 ke upar rakho CGPA
2. Core ki companies kam aati hain.

More so, ab aur kaam karne ka mann nahi hai bhai.
